version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=letmein
      - POSTGRES_DB=test_db
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
  roche-products:
    image: roche-products:latest
    container_name: roche-products
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=local

networks:
  my_network:
    driver: bridge